server:
  port: 8183
  servlet:
    context-path: /web-market-rec
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./recommendations;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  core-service:
    url: http://localhost:5555/core
    timeouts:
      connect: 2000
      read: 10000
      write: 2000
  cart-service:
    url: http://localhost:5555/cart
    timeouts:
      connect: 2000
      read: 10000
      write: 2000